import os

ENV_API_URL = "NETGARDE_API_URL"
ENV_API_TOKEN = "NETGARDE_API_TOKEN"

DEFAULT_ENROLL_PATH = "/v1/enroll"
DEFAULT_USAGE_PATH = "/v1/usage"
DEFAULT_POLICY_CA_PATH = "/policy/block-page-ca"
DEFAULT_WINTUN_NAME = "NetGarde"
DEFAULT_WIREGUARD_PORT = "51820"
DEFAULT_MTU = 1420

MAX_ENROLL_RESPONSE_BYTES = 1 << 20
HTTP_CLIENT_TIMEOUT = 60
ENDPOINT_RESOLVE_TIMEOUT = 15

STATE_FILE_PERM = 0o600
CACHED_WG_CONF_PERM = 0o600
